In [1]:
%pip install ipykernel matplotlib numpy pandas scikit-learn seaborn

Requirement already satisfied: ipykernel in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (7.2.0)
Requirement already satisfied: matplotlib in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (3.10.8)
Requirement already satisfied: numpy in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (2.4.2)
Requirement already satisfied: pandas in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (3.0.1)
Requirement already satisfied: scikit-learn in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (1.8.0)
Requirement already satisfied: seaborn in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (0.13.2)
Requirement already satisfied: comm>=0.1.1 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (9.11.0)
Requirement already satisfied: jupyter-client>=8.8.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (26.0)
Requirement already satisfied: psutil>=5.7 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (6.5.4)
Requirement already satisfied: traitlets>=5.4.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: decorator>=5.1.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: pexpect>4.6 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipython>=7.23.1->ipykernel) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipython>=7.23.1->ipykernel) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.6)
Requirement already satisfied: platformdirs>=2.5 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.4)
Requirement already satisfied: ptyprocess>=0.5 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from pexpect>4.6->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in /home/thiagola92/.local/share/pipx/venvs/jupyterlab/lib64/python3.14/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import numpy
import pandas
import seaborn
from pathlib import Path
from zipfile import ZipFile
from matplotlib import pyplot
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

In [2]:
if not Path("dataset.csv").exists():
    ZipFile("dataset.zip").extract("dataset.csv")

dataset = pandas.read_csv("dataset.csv")

pandas.set_option("display.max_columns", None)
pandas.set_option('display.max_colwidth', None)
dataset.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,NoOfObfuscatedChar,ObfuscationRatio,NoOfLettersInURL,LetterRatioInURL,NoOfDegitsInURL,DegitRatioInURL,NoOfEqualsInURL,NoOfQMarkInURL,NoOfAmpersandInURL,NoOfOtherSpecialCharsInURL,SpacialCharRatioInURL,IsHTTPS,LineOfCode,LargestLineLength,HasTitle,Title,DomainTitleMatchScore,URLTitleMatchScore,HasFavicon,Robots,IsResponsive,NoOfURLRedirect,NoOfSelfRedirect,HasDescription,NoOfPopup,NoOfiFrame,HasExternalFormSubmit,HasSocialNet,HasSubmitButton,HasHiddenFields,HasPasswordField,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,3,1,0,0,0.0,18,0.581,0,0.0,0,0,0,1,0.032,1,558,9381,1,à¸‚à¹ˆà¸²à¸§à¸ªà¸” à¸‚à¹ˆà¸²à¸§à¸§à¸±à¸™à¸™à¸µà¹‰ à¸‚à¹ˆà¸²à¸§à¸à¸µà¸¬à¸² à¸‚à¹ˆà¸²à¸§à¸šà¸±à¸™à¹€à¸—à¸´à¸‡ à¸­à¸±à¸žà¹€à¸”à¸—à¸ªà¸”à¹ƒà¸«à¸¡à¹ˆà¸—à¸¸à¸à¸§à¸±à¸™ &#8211; à¸‚à¹ˆà¸²à¸§à¸ªà¸” à¸‚à¹ˆà¸²à¸§à¸à¸µà¸¬à¸² à¸‚à¹ˆà¸²à¸§à¸šà¸±à¸™à¹€à¸—à¸´à¸‡ à¸‚à¹ˆà¸²à¸§à¸§à¸±à¸™à¸™à¸µà¹‰ à¸­à¸±à¸›à¹€à¸”à¸•à¸‚à¹ˆà¸²à¸§à¸ªà¸²à¸£à¸£à¸§à¸”à¹€à¸£à¹‡à¸§à¸—à¸±à¸™à¹ƒà¸ˆ à¸žà¸£à¹‰à¸­à¸¡à¸£à¸±à¸šà¸Šà¸¡à¸ªà¸²à¸£à¸°à¸™à¹ˆà¸²à¸£à¸¹à¹‰à¸•à¹ˆà¸²à¸‡à¹† à¹„à¸”à¹‰à¸Ÿà¸£à¸µà¸•à¸¥à¸­à¸” 24à¸Šà¸±à¹ˆà¸§à¹‚à¸¡à¸‡,0.000000,0.000000,0,1,1,0,0,0,0,1,0,0,1,1,0,1,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,2,1,0,0,0.0,9,0.391,0,0.0,0,0,0,2,0.087,1,618,9381,1,johannes gutenberg-universitÃ¤t mainz,55.555556,55.555556,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,2,2,0,0,0.0,15,0.517,0,0.0,0,0,0,2,0.069,1,467,682,1,voice fm southampton,46.666667,46.666667,0,1,1,0,0,1,0,0,0,0,1,1,0,0,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,3,1,0,0,0.0,13,0.500,0,0.0,0,0,0,1,0.038,1,6356,26824,1,home page: seminars in fetal and neonatal medicine,0.000000,0.000000,0,1,1,0,0,0,1,12,0,1,1,1,0,0,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,3,1,0,0,0.0,20,0.606,0,0.0,0,0,0,1,0.030,1,6089,28404,1,fundaciÃ³n rewilding argentina,100.000000,100.000000,0,1,1,1,1,1,0,2,0,1,1,1,0,1,1,0,1,244,15,34,72,1,85,1

In [3]:
dataset["label"].value_counts()

label
1    134850
0    100945
Name: count, dtype: int64

In [4]:
dataset.columns

Index(['FILENAME', 'URL', 'URLLength', 'Domain', 'DomainLength', 'IsDomainIP',
       'TLD', 'URLSimilarityIndex', 'CharContinuationRate',
       'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain',
       'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio',
       'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL',
       'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL',
       'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL',
       'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength',
       'HasTitle', 'Title', 'DomainTitleMatchScore', 'URLTitleMatchScore',
       'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect',
       'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame',
       'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton',
       'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto',
       'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef',
       'NoOfEmptyRef', 'NoOfExternalRef', 'label'],
      dtype='str')

In [40]:
dataset[["URL", "URLCharProb"]]

                                                             URL  URLCharProb
0                               https://www.southbankmosaics.com     0.061933
1                                       https://www.uni-mainz.de     0.050207
2                                 https://www.voicefmradio.co.uk     0.064129
3                                    https://www.sfnmjournal.com     0.057606
4                             https://www.rewildingargentina.org     0.059441
...                                                          ...          ...
235790                            https://www.skincareliving.com     0.058739
235791                             https://www.winchester.gov.uk     0.053834
235792                           https://www.nononsensedesign.be     0.063093
235793  https://patient-cell-40f5.updatedlogmylogin.workers.dev/     0.050211
235794                        https://www.alternativefinland.com     0.060596

[235795 rows x 2 columns]

In [22]:
dataset[["URL", "TLD", "TLDLength", "TLDLegitimateProb"]].query("TLD == 'com'")

                                       URL  TLD  TLDLength  TLDLegitimateProb
0         https://www.southbankmosaics.com  com          3           0.522907
3              https://www.sfnmjournal.com  com          3           0.522907
6               https://www.saffronart.com  com          3           0.522907
7               https://www.nerdscandy.com  com          3           0.522907
10      https://www.religionenlibertad.com  com          3           0.522907
...                                    ...  ...        ...                ...
235785   https://www.virginiakraljevic.com  com          3           0.522907
235788            https://www.karibpan.com  com          3           0.522907
235789     https://www.life-in-ecuador.com  com          3           0.522907
235790      https://www.skincareliving.com  com          3           0.522907
235794  https://www.alternativefinland.com  com          3           0.522907

[112554 rows x 4 columns]

In [26]:
dataset[["TLD", "label"]].value_counts()

TLD   label
com   1        68785
      0        43769
org   1        16524
app   0         6368
uk    1         6073
               ...
ist   0            1
film  1            1
bh    0            1
tj    0            1
ne    1            1
Name: count, Length: 1029, dtype: int64

In [31]:
dataset[["TLD", "TLDLegitimateProb"]].drop_duplicates()

           TLD  TLDLegitimateProb
0          com           0.522907
1           de           0.032650
2           uk           0.028555
4          org           0.079963
8           in           0.005084
...        ...                ...
225491     151           0.000000
227723  madrid           0.000002
230438      46           0.000000
231941    film           0.000034
235390      ne           0.000017

[695 rows x 2 columns]

In [36]:
dataset[["TLD", "TLDLegitimateProb"]].drop_duplicates().to_csv("tld_legitimate_prob.csv", index=False)